/** Parity gate (PLAN 7.2): the highest-value test in the project.
 *
 * The fixtures in web/test/fixtures/*.json were generated by the PYTHON
 * implementation (vdrum.testgen.gen_cases / write_fixtures): each holds a
 * track + config and the EXACT hit list Python produced. This test runs the
 * TS port (web/src/detect.ts) over the same inputs and asserts the same hit
 * list, bit-for-bit. Same model, same version, same numbers -- any drift in
 * the port fails here.
 *
 * Driven from pre-extracted data (JSON), never from a <video> element, so
 * browser decode non-determinism cannot flake the gate (PLAN 7.2).
 */
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { configFromDict } from "../src/config";
import { detect, type Track } from "../src/detect";
import { ZoneSet } from "../src/zones";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIX = path.join(HERE, "fixtures");
const ROOT = path.join(HERE, "..", "..");

function loadZones(): ZoneSet {
  const raw = JSON.parse(
    readFileSync(path.join(ROOT, "config", "zones.json"), "utf8"),
  );
  return ZoneSet.fromDict(raw);
}

function loadTrack(raw: {
  track: { t_ms: number[]; hands: string[] } & Record<string, unknown>;
}): Track {
  const track: Track = { t_ms: raw.track.t_ms, channels: {} };
  for (const h of raw.track.hands) {
    track.channels[h] = raw.track[h] as Track["channels"][string];
  }
  return track;
}

const files = readdirSync(FIX)
  .filter((f) => f.endsWith(".json"))
  .sort();

describe("parity gate (PLAN 7.2)", () => {
  it("found the generated fixtures", () => {
    expect(files.length).toBe(12);
  });

  for (const f of files) {
    it(`TS detect === Python expected: ${f}`, () => {
      const raw = JSON.parse(readFileSync(path.join(FIX, f), "utf8"));
      const cfg = configFromDict(raw.config);
      const track = loadTrack(raw);
      const zones = loadZones();

      const hits = detect(track, cfg, zones);
      const exp = raw.expected;

      expect(hits.length).toBe(exp.count);
      for (let i = 0; i < hits.length; i++) {
        const h = hits[i];
        const e = exp.hits[i];
        expect(h.report_t_ms).toBe(e.t_ms);
        expect(h.peak_t_ms).toBe(e.peak_t_ms);
        expect(h.hand).toBe(e.hand);
        expect(h.zone).toBe(e.zone);
        expect(h.velocity).toBe(e.velocity);
      }
    });
  }
});
